-- DDL generated by Postico 1.5.20
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE favorites (
    gist_id character varying(32) PRIMARY KEY,
    user_id character varying(40) NOT NULL
);

-- Indices -------------------------------------------------------

CREATE INDEX favorites_user_id_idx ON favorites(user_id text_ops);
